# Generated by Django 4.2.10 on 2024-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_channel_media_channelarticle_article_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=25, verbose_name='Канал')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('intro', models.CharField(max_length=250, verbose_name='Анонс')),
                ('content', models.TextField(blank=True, verbose_name='Статья')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время редакции')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус публикации')),
            ],
        ),
    ]
